services:
  mysql:
    build:
      context: ./mysql
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/mysql
    expose:
      - "5655"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pexample"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./app
    image: app
    networks:
      - db_network
      - site_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_container
    ports:
      - "5423:824"
    networks:
      - site_network
    depends_on:
      app:
        condition: service_healthy

volumes:
  db_volume:

networks:
  db_network:
  site_network:
